version: '3'

services:
  redis:
    image: redis:7.2.4-alpine3.19
    ports:
      - 6379:6379
  mainservice:
    build: 
      context: ./main_service
    environment:
      PYTHONUNBUFFERED: "TRUE" # gunicorn waits for buffer to fill up only then it logs. This will instruct gunicorn to log instantly.
    command: gunicorn core.wsgi -w 3 --bind 0.0.0.0:8080
    # command: python manage.py runserver 0.0.0.0:8080
    # ports:
    #   - "8000:8000"
  tokenservice:
    build: 
      context: ./token_service
    environment:
      PYTHONUNBUFFERED: "TRUE" # gunicorn waits for buffer to fill up only then it logs. This will instruct gunicorn to log instantly.
    command: gunicorn core.wsgi -w 3 --bind 0.0.0.0:8000
    # command: python manage.py runserver 0.0.0.0:8000
    # ports:
    #   - "8000:8000"
  nginx:
    image: nginx:latest
    ports:
      - 8001:8001
    volumes:
      - ./nginx/nginx.setup.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - redis
      - mainservice
      - tokenservice